parameters:
    mindy.template.path: '%kernel.root_dir%/Resources/templates'
    mindy.template.theme: default
    mindy.template.mode: 0
    mindy.template.exception_handler: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Mindy\Template\Library\LibraryInterface:
            tags: ['template.library']

        Mindy\Template\VariableProviderInterface:
            tags: ['template.variable_provider']

    Mindy\Bundle\TemplateBundle\:
        resource: '../../*'
        exclude: '../../{Tests,vendor}'

    Mindy\Template\Finder\TemplateFinder:
        public: true
        arguments:
            - '%kernel.root_dir%/Resources/templates'

    Mindy\Bundle\TemplateBundle\Finder\ThemeTemplateFinder:
        public: true
        arguments:
            $themesPath: '%kernel.root_dir%/Resources/themes'
            $theme: '%mindy.template.theme%'

    Mindy\Bundle\TemplateBundle\Finder\BundleTemplateFinder:
        public: true
        arguments:
            $bundles: '@=container.get("kernel").getBundles()'

    Mindy\Template\Finder\ChainFinder:
        public: true
        arguments:
            $finders: ['@Mindy\Bundle\TemplateBundle\Finder\ThemeTemplateFinder', '@Mindy\Template\Finder\TemplateFinder', '@Mindy\Bundle\TemplateBundle\Finder\BundleTemplateFinder']

    Mindy\Template\TemplateEngine:
        public: true
        arguments:
            $finder: '@Mindy\Template\Finder\ChainFinder'
            $target: '%mindy.template.path%'
            $mode: '%mindy.template.mode%'
            $exceptionHandler: '%mindy.template.exception_handler%'

    templating.engine.mindy:
        alias: Mindy\Template\TemplateEngine
        public: true
